include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
    use_key_in_widget_constructors: true

analyzer:
  exclude:
    - build/**
    - .dart_tool/**