workflows:
  android-release:
    name: Android Release
    environment:
      flutter: stable
    scripts:
      - rm -f pubspec.lock   # <--- أضف هذا السطر
      - flutter pub get
      - flutter build apk --split-per-abi
    artifacts:
      - build/app/outputs/apk/**/*.apk
